INSERT INTO collections (COLLECTION_NAME) values
                                      ('The 2018 Inferno Collection'),
                                      ('The 2018 Nuke Collection'),
                                      ('The Bank Collection'),
                                      ('The Dust 2 Collection'),
                                      ('The Italy Collection'),
                                      ('The Lake Collection'),
                                      ('The Safehouse Collection'),
                                      ('The Train Collection'),
                                      ('Limited Edition Item'),
                                      ('The Graphic Design Collection'),
                                      ('The Overpass 2024 Collection'),
                                      ('The Sport & Field Collection'),
                                      ('The 2021 Dust 2 Collection'),
                                      ('The 2021 Mirage Collection'),
                                      ('The 2021 Train Collection'),
                                      ('The 2021 Vertigo Collection'),
                                      ('The Ancient Collection'),
                                      ('The Control Collection'),
                                      ('The Havoc Collection'),
                                      ('The Canals Collection'),
                                      ('The Norse Collection'),
                                      ('The St. Marc Collection'),
                                      ('The Cache Collection'),
                                      ('The Chop Shop Collection'),
                                      ('The Cobblestone Collection'),
                                      ('The Gods and Monsters Collection'),
                                      ('The Overpass Collection'),
                                      ('The Rising Sun Collection'),
                                      ('The Anubis Collection'),
                                      ('The Assault Collection'),
                                      ('The Aztec Collection'),
                                      ('The Baggage Collection'),
                                      ('The Gallery Collection'),
                                      ('The Kilowatt Collection'),
                                      ('The Revolution Collection'),
                                      ('The Recoil Collection'),
                                      ('The Dreams & Nightmares Collection'),
                                      ('The Operation Riptide Collection'),
                                      ('The Snakebite Collection'),
                                      ('The Operation Broken Fang Collection'),
                                      ('The Fracture Collection'),
                                      ('The Prisma 2 Collection'),
                                      ('The Shattered Web Collection'),
                                      ('The CS20 Collection'),
                                      ('The X-Ray Collection'),
                                      ('The Prisma Collection'),
                                      ('The Clutch Collection'),
                                      ('The Blacksite Collection'),
                                      ('The Danger Zone Collection'),
                                      ('The Horizon Collection'),
                                      ('The Spectrum 2 Collection'),
                                      ('Operation Hydra'),
                                      ('The Glove Collection'),
                                      ('The Gamma 2 Collection'),
                                      ('The Gamma Collection'),
                                      ('The Chroma 3 Collection'),
                                      ('The Wildfire Collection'),
                                      ('The Revolver Case Collection'),
                                      ('The Shadow Collection'),
                                      ('The Falchion Collection'),
                                      ('The Chroma 2 Collection'),
                                      ('The Chroma Collection'),
                                      ('The Vanguard Collection'),
                                      ('The eSports 2014 Summer Collection'),
                                      ('The Breakout Collection'),
                                      ('The Huntsman Collection'),
                                      ('The Phoenix Collection'),
                                      ('The Arms Deal 3 Collection'),
                                      ('The Winter Offensive Collection'),
                                      ('The eSports 2013 Winter Collection'),
                                      ('The Mirage Collection'),
                                      ('The Arms Deal 2 Collection'),
                                      ('The Bravo Collection'),
                                      ('The Alpha Collection'),
                                      ('The Vertigo Collection'),
                                      ('The Office Collection'),
                                      ('The Militia Collection'),
                                      ('The eSports 2013 Collection'),
                                      ('The Nuke Collection'),
                                      ('The Inferno Collection'),
                                      ('The Dust Collection'),
                                      ('The Arms Deal Collection'),
                                      ('The Operation Hydra Collection'),
                                      ('The Spectrum Collection')